### ISSUE TITLE
ArgumentError:  file or block required

### ISSUE THREAD

**Issue by subvertallchris** [anthonator/tilt-jbuilder#16]
I'm running into this whenever I call `json.partial!`. Sinatra 1.4.5, tilt-1.4.1, til-jbuilder-0.6.1. I can get it to load a template if I do this:

```
template = Tilt::JbuilderTemplate.new 'index.jbuilder'
```
But if I try to use the block or call `json.partial!`, I get the error in the title. Any help is appreciated!

**Comment by anthonator** [comment]
Can you snd some code over the exhibits the behavior?

**Comment by subvertallchris** [comment]
Sure, but it's not too exciting. 

module Sinatra
  module APIv1::Reports

    def self.registered(app)
      app.namespace %r{^/v1} do
        get '/reports/?' do
          template = Tilt::JbuilderTemplate.new("#{app.views}/v1/reports/index.json.jbuilder")
          template.render
        end
      end
    end
  end

  register APIv1::Reports
end

Then within `index.json.jbuilder`...

```
json.partial! :partial_name
```
...results in...
```
     ArgumentError:
       file or block required
     # /Users/cgrigg/.rvm/gems/ruby-2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:51:in `initialize'
     # /Users/cgrigg/.rvm/gems/ruby-2.2.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:14:in `new'
     # /Users/cgrigg/.rvm/gems/ruby-2.2.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:14:in `partial!'
     # ./app/views/v1/reports/index.json.jbuilder:1:in `block (2 levels) in evaluate'
```

I think it's happening because `view_path` is returning nil at  https://github.com/anthonator/tilt-jbuilder/blob/master/lib/tilt/jbuilder.rb#L13.

**Comment by subvertallchris** [comment]
If I make this adjustment:

```
    def partial!(template_name, locals = {})
      locals.merge! :json => self
      template_path = locals.extract!(:template_path)[:template_path]
      view_path = @scope.instance_variable_get('@_jbuilder_view_path') || template_path
      file = fetch_partial_path(template_name.to_s, view_path)
      template = ::Tilt::JbuilderTemplate.new(file, nil, view_path: view_path)
      template.render(@scope, locals)
    end
```

I'm able to do this in my template:

```
json.partial!('v1/reports/omg', template_path: Sinatra::Application.views)
```

And it works. Would love not to do this but it'll work for the time being.

**Comment by anthonator** [comment]
Sorry for not being very responsive!

Does jbuilder let you provide a symbol to render a partial? I don't think it does. Is there a reason you need to use a partial over a string?

**Comment by anthonator** [comment]
Closing due to lack of response. Reopen if you would still like to discuss.
