### ISSUE TITLE
Partial error message

### ISSUE THREAD

**Issue by triplepointfive** [anthonator/tilt-jbuilder#18]
Rendering partials like `json.partial! 'sizes'` with non existing file fails with `ArgumentError - file or block required`.
That's a bit frustrating when there is a typo in a file name, because I definitely pass the file.
Tilt has a special error for this case `TypeError, "Can't load the template file. Pass a string with a path ...` I guess this is the expected error in case when file couldn't be found.

**Comment by anthonator** [comment]
Closing this as there's been no movement and nobody else has mentioned this. Feel free to open another issue or submit a PR if you'd like to see this resolved.
